version: '3.8'

services:
  web:
    image: node:15.12.0-alpine3.10
    working_dir: /application
    command: /bin/sh -c "npm install && npm run serve"
    ports:
      - "8080:8080"
    volumes:
      - .:/application
    restart: unless-stopped